### ISSUE TITLE
How to test the crawl module

### ISSUE THREAD

**Issue by markosii** [emadehsan/thal#26]
Hi, 

I'm a new user for your module, I icorrectly installed Node and MongoDB

I did this : 

`git clone https://github.com/emadehsan/thal.git`

`cd thal`

`npm install`

=> modules are correctly installed

I don't know how can I run it? can you tell me plz

when I did `npm test`, I have this error 

```
> thal@1.0.0 test /root/puppeteer/thal
> echo "Error: no test specified" && exit 1

Error: no test specified
npm ERR! Test failed.  See above for more details.
```

I tried `node index.js`, I have this error

```
module.js:491
    throw err;
    ^

Error: Cannot find module './creds'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/puppeteer/thal/index.js:2:15)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

Thanks

**Comment by emadehsan** [comment]
Hi @markosii if you go to here https://github.com/emadehsan/thal#login-to-github you would see

> Add a file creds.js in project root. I highly recommend signing up for new account with a new dummy 
email because you might end up getting your account blocked. 

Put following content inside
```
module.exports = {
    username: '<GITHUB_USERNAME>',
    password: '<GITHUB_PASSWORD>'
}
```

**Comment by markosii** [comment]
Thank you, this work with authotification

But I Have this error 
```

D:\Apps\puppeteer\thal>node index.js
numUsers:  83001
Numpages:  8301
jhawthorn  ->  john@hawthorn.email
(node:3120) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
JohnSundell  ->  john@sundell.co
jbarnette  ->  john@jbarnette.com
jdegoes  ->  john@degoes.net
JohnMcLear  ->  john@mclear.co.uk
jmhobbs  ->  john@velvetcache.org
jr0cket  ->  john@jr0cket.co.uk
johndrinkwater  ->  john@johndrinkwater.name
jwang  ->  john@johntwang.com

events.js:183
      throw er; // Unhandled 'error' event
      ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (D:\Apps\puppeteer\thal\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (D:\Apps\puppeteer\thal\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (D:\Apps\puppeteer\thal\node_modules\mongodb-core\lib\connection\connection.js:187:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

D:\Apps\puppeteer\thal>
```

**Comment by markosii** [comment]
Thanks it works :)
